### ISSUE TITLE
中文显示乱码

### ISSUE THREAD

**Issue by faiz-lab** [dextercai/JavaQuizCode#1]
![image](https://user-images.githubusercontent.com/53805895/102966246-793e4880-452a-11eb-8472-052ead2b075b.png)

**Comment by dextercai** [comment]
I will fix it later. BTW, using image will cause a bad reading experience, sometimes.

**Comment by dextercai** [comment]
[Commit 236ed50](https://github.com/dextercai/JavaQuizCode/commit/236ed5074284e5d5a8be00f2bc69599eef5cfa41)
Fixed
